apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-demo
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
      ports:
        - containerPort: 80
    - name: redis-container
      image: redis:7
    - name: busybox-container
      image: busybox:stable
      command: ["sh", "-c", "while true; do echo busybox-working; sleep 10; done"]
    - name: curl-container
      image: curlimages/curl:8.8.0
      command: ["sh", "-c", "while true; do echo curl-container-ready; sleep 15; done"]